### PR TITLE
reflect requirement for settings cdc_ncm

### PR DESCRIPTION
**Pull request by virmaior**
Let's just say I spent hours trying to configure my raspberry pi and that was all because I misunderstood this one simple detail about flags.

### CODE REVIEW

**Comment by gtxaspec** [comment]
hmm, it **_shouldn't_** require ENABLE_USB_ETH also.

**Comment by virmaior** [comment]
Here was my experience:
1. test powered hub's ability to display usb devices using a usb drive (obviously was going to work and did)
2. prepare 16 GB FAT32 SD card with ENABLE_USB_DIRECT=true, USB_DIRECT_MAC_ADDR = ... , disable firmware updates
3. plug in to powered hub.
4. Hear audio that it set up successfully for wz_mini
5. try to figure out why it wasn't working (which was rather difficult to search for because most things are about setting up a RPI in gadget mode).
6. Install the dwc2 overlay and cdc_ncm module (this is what I figured out from reading the openwrt documentation and some other sources).
7. Keep trying different things with no results for the configuration on the pi etc (such as huawei_cdc_ncm)
8. Test a usb-ethernet adapter capable in the hub - it works normally.
9. try ENABLE_USB_RNDIS="false" instead of USB_DIRECT (not expecting it to work but as troubleshooting -- it didn't)
10. try USB_ETH and USB_DIRECT both true

For steps 1-8, no usb device appeared in lsusb and no indication of a usb network in network configuration
Now the raspberry pi sees the device and starts up a usb0 network interface for it (that's the end of what I can work on today for it).

**Comment by virmaior** [comment]
dmesg output from the boot where it worked:
[   37.203411] usbcore: registered new interface driver cdc_ether
[   37.209209] usbcore: registered new interface driver cdc_ncm
[  512.532810] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.eth0.retrans_time - use net.ipv6.neigh.eth0.retrans_time_ms instead
[  931.024790] usbcore: registered new interface driver cdc_wdm
[  931.026207] usbcore: registered new interface driver huawei_cdc_ncm
[ 1181.310040] usb 2-2.1.3: new SuperSpeed Gen 1 USB device number 5 using xhci_hcd
[ 1181.589346] usb 2-2.1.3: New USB device found, idVendor=0b95, idProduct=1790, bcdDevice= 2.00
[ 1181.589368] usb 2-2.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1181.589387] usb 2-2.1.3: Product: AX88179A
[ 1181.589405] usb 2-2.1.3: Manufacturer: ASIX
[ 1181.589422] usb 2-2.1.3: SerialNumber: 00621BF7
[ 1181.835824] cdc_ncm 2-2.1.3:2.0: MAC-Address: f8:e4:3b:62:1b:f7
[ 1181.835847] cdc_ncm 2-2.1.3:2.0: setting rx_max = 16384
[ 1181.847392] cdc_ncm 2-2.1.3:2.0: setting tx_max = 16384
[ 1181.867759] cdc_ncm 2-2.1.3:2.0 eth1: register 'cdc_ncm' at usb-0000:01:00.0-2.1.3, CDC NCM, f8:e4:3b:62:1b:f7
[ 1181.952903] usbcore: registered new interface driver ax88179_178a
[ 1181.955418] usbcore: registered new interface driver cdc_mbim
[ 2082.730879] usb 1-1.2.1.2: new high-speed USB device number 5 using xhci_hcd
[ 2082.861617] usb 1-1.2.1.2: New USB device found, idVendor=0525, idProduct=a4a1, bcdDevice= 3.10
[ 2082.861639] usb 1-1.2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2082.861658] usb 1-1.2.1.2: Product: NCM Gadget
[ 2082.861675] usb 1-1.2.1.2: Manufacturer: wz_mini_ncm
[ 2082.892493] cdc_ncm 1-1.2.1.2:1.0: MAC-Address: f6:8e:bb:f4:60:e8
[ 2082.893514] cdc_ncm 1-1.2.1.2:1.0 usb0: register 'cdc_ncm' at usb-0000:01:00.0-1.2.1.2, CDC NCM, f6:8e:bb:f4:60:e8
[ 2083.068969] cdc_ncm 1-1.2.1.2:1.0 usb0: 425 mbit/s downlink 425 mbit/s uplink
[ 2083.517087] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
[ 2115.148708] usb 1-1.2.1.2: USB disconnect, device number 5
[ 2115.149226] cdc_ncm 1-1.2.1.2:1.0 usb0: unregister 'cdc_ncm' usb-0000:01:00.0-1.2.1.2, CDC NCM
[ 2299.912592] usb 1-1.2.1.2: new high-speed USB device number 6 using xhci_hcd
[ 2300.043193] usb 1-1.2.1.2: New USB device found, idVendor=0525, idProduct=a4a1, bcdDevice= 3.10
[ 2300.043204] usb 1-1.2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2300.043211] usb 1-1.2.1.2: Product: NCM Gadget
[ 2300.043218] usb 1-1.2.1.2: Manufacturer: wz_mini_ncm
[ 2300.073998] cdc_ncm 1-1.2.1.2:1.0: MAC-Address: 0a:de:87:d8:05:e4
[ 2300.074491] cdc_ncm 1-1.2.1.2:1.0 usb0: register 'cdc_ncm' at usb-0000:01:00.0-1.2.1.2, CDC NCM, 0a:de:87:d8:05:e4
[ 2300.216091] cdc_ncm 1-1.2.1.2:1.0 usb0: 425 mbit/s downlink 425 mbit/s uplink
[ 2300.568187] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
[ 2842.096573] usb 1-1.2.1.2: USB disconnect, device number 6
[ 2842.097176] cdc_ncm 1-1.2.1.2:1.0 usb0: unregister 'cdc_ncm' usb-0000:01:00.0-1.2.1.2, CDC NCM
[ 3279.350362] usb 1-1.2.1.2: new high-speed USB device number 7 using xhci_hcd
[ 3279.481084] usb 1-1.2.1.2: New USB device found, idVendor=0525, idProduct=a4a1, bcdDevice= 3.10
[ 3279.481107] usb 1-1.2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3279.481125] usb 1-1.2.1.2: Product: NCM Gadget
[ 3279.481143] usb 1-1.2.1.2: Manufacturer: wz_mini_ncm
[ 3279.512014] cdc_ncm 1-1.2.1.2:1.0: MAC-Address: ea:45:17:14:04:f4
[ 3279.512984] cdc_ncm 1-1.2.1.2:1.0 usb0: register 'cdc_ncm' at usb-0000:01:00.0-1.2.1.2, CDC NCM, ea:45:17:14:04:f4
[ 3279.665979] cdc_ncm 1-1.2.1.2:1.0 usb0: 425 mbit/s downlink 425 mbit/s uplink
[ 3280.050067] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
[ 3742.675505] usb 1-1.2.1.2: USB disconnect, device number 7
[ 3742.676042] cdc_ncm 1-1.2.1.2:1.0 usb0: unregister 'cdc_ncm' usb-0000:01:00.0-1.2.1.2, CDC NCM

The AX88179A is the usb ethernet adapter.

**Comment by gtxaspec** [comment]
The cable wyze supplies indeed does not work.  I will update the readme with this. 

Question:
1. are you using the latest versions that don't need the USB_DIRECT version of the factory t31 file?

**Comment by virmaior** [comment]
**oh wow, so it was the cable.**

I'm using the version immediately prior to the one you uploaded today, so yes.

Thanks for all of your hard work on this!!!

**Pull request closed without merging**
