### PR TITLE
Add support for auto detecting the USB Ethernet adapter, and loading its respective driver

### PR DESCRIPTION
**Pull request by skilau**
My goal is to have 1 common .conf file between all my cameras, even if they might have different USB NIC adapters.

This change adds support for auto-detecting what Ethernet adapter they have, and loading only the driver they need.

This also removes 1 option from the conf file now, since they no longer need to specify the adapter in "ENABLE_USB_ETH_MODULES"

NOTE:  I don't have a NIC here to add the ids for cdc_ether and r8152.

So if this patch is accepted, we will need to test a few of them, and then add the various ids that are listed in their respective driver.c files in the kernel sources.

### CODE REVIEW

**Comment by gtxaspec** [comment]
@skilau, can you modify this do allow the user to force specific module loading?  

As in, if  "`$ENABLE_USB_ETH_MODULES" != ""` then load the module specified, but if its `""` (blank) then do the auto load?

**Comment by gtxaspec** [comment]
should we leave it at `=""`, or, would `="automatic"` be more user-friendly, @skilau ?

**Comment by skilau** [comment]
I had another idea, but wasn't sure if you would like it or not.

What about if we have a new variable called:
ENABLE_USB_ETH_AUTODETECT="true"/"false"

If it is set to true, we do the automatic/autodetect part, if set to false, it attempts to load whatever driver is listed in ENABLE_USB_ETH_MODULE

**Comment by gtxaspec** [comment]
looks good

**Pull request merged**
