### PR TITLE
Rudimentary webserver over httpd

### PR DESCRIPTION
**Pull request by virmaior**
works. not much else to say about it. Could use lots of improvements.

### CODE REVIEW

**Comment by gtxaspec** [comment]
awesome.  I'll try to figure out how to implement a web version of `car_control.sh` so we can control from the web instead of the command line too!

**Comment by virmaior** [comment]
I've updated it to add the following functionality:
1. by renaming wz_mini_web.sh to index.cgi , it will automatically be the default page at the IP address: 192.168.9.101 
2. added support for showing the hack version correctly with hackver=$(cat /opt/wz_mini/usr/bin/app.ver)
3. added support for explanatory text on the right. match the name of the file to key.md and it will load it at that row.

**Comment by gtxaspec** [comment]
do you mind renaming the directory to www instead of web? just to keep it uniform with unix stuff

**Comment by virmaior** [comment]
I moved everything including references from web to www

**Comment by gtxaspec** [comment]
sweet, I will go ahead and merge with master

**Comment by gtxaspec** [comment]
@virmaior oh one more thing, can you copy wz_mini.conf with your variable change to etc/wz_mini.conf.dist 

thanks

**Comment by virmaior** [comment]
done!

**Comment by virmaior** [comment]
but maybe it should default to false?

**Comment by gtxaspec** [comment]
yes I agree

**Comment by virmaior** [comment]
It's done! (or it should be)

**Pull request merged**
