### PR TITLE
cam config www bricking fixed

### PR DESCRIPTION
**Pull request by virmaior**
-I rewrote the cam.cgi code so that it only replaces lines that are changed via a javascript check on submit for changes and then rewriting of only that line based on the key name. (This time I tested it and am getting the correct results, still quite a bit wary of changing these values myself).
-I modified the interface of cam.cgi using https://github.com/gtxaspec/wz_mini_hacks/discussions/309#discussion-4409288 . Basically I cut and paste that into a text file (this actually took longer than the the first fix ... even though it's easier. IFS ...)
- Through JavaScript, synchronize changes between the dropdown and direct entry for cam.cgi

### CODE REVIEW

**Comment by gtxaspec** [comment]
@virmaior,

when i exit the timezone line, for example,

it goes to this:

`TZ_STR=EST%2B0800EST%2B0700%2CM3.2.0%2F02%3A00%3A00%2CM11.1.0%2F02%3A00%3A00`

from this:
`TZ_STR=PST+0800PDT+0700,M3.2.0/02:00:00,M11.1.0/02:00:00`

**Comment by virmaior** [comment]
(It's probably because I'm still on 4.36.2.5 but I don't have entries that look that in my file)
I presume you mean "edit" instead of "exit"?

interesting. It looks like it's escaping the values. I'll have to check whether that's happening through httpd's cgi-bin or whether my code is inadvertently doing that (my initial guess is the former).

**Comment by virmaior** [comment]
looks like this is already in the POST data when it enters the script from cgi-bin so I'll have to unescape ...
(references:
https://www.oreilly.com/library/view/cgi-programming-on/9781565921689/07_chapter-04.html
https://www.infor.uva.es/~jvegas/cursos/web/cgi-bin/fuentes/readdata.html
)

will test this sorcery : https://stackoverflow.com/questions/6250698/how-to-decode-url-encoded-string-in-shell 
when I get the chance

**Comment by virmaior** [comment]
okay. fixed now.
none of the samples scripts worked (thanks ash!) but it wasn't that hard to implement it based on that info.
tested for both `cam.cgi` and `config.cgi`

**Pull request merged**
